### ISSUE TITLE
Main page is broken

### ISSUE THREAD

**Issue by skyblockz** [slothpixel/core#292]
The main page of slothpixel (https://slothpixel.me) was supposed to work like a homepage or something else, but this is what happens when you open it
https://prnt.sc/qlqss9
Is this intended? Or is it an failure of the homepage? Please tell me thanks!

**Comment by builder-247** [comment]
We are currently in the process of updating the homepage to a newer version and cloudflare SSL is causing a redirect loop. The new page should be up within a week.

**Comment by Ryamonster10** [comment]
Home page still not up!

**Comment by builder-247** [comment]
> Home page still not up!

It won't be until the slothpixel site is at a releasable state. You can make this happen faster by contributing to [slothpixel/ui](https://github.com/slothpixel/ui).
