### ISSUE TITLE
Support human readable timestamp parameters

### ISSUE THREAD

**Issue by builder-247** [slothpixel/core#359]
[Grafana](https://github.com/grafana/grafana/) has a wonderful feature that supports human friendly way of representing dates in parameters, for example `?from=now-7d&to=now` would select the timeframe of past week. Multiple different arithmetic operations are supported.

Scope of this enhancement is to convert the functionality to slothpixel date-related parameters. I've already got started (a little) on this - the work can be seen on the [datemath](https://github.com/slothpixel/core/tree/datemath) branch.

Related files: https://github.com/grafana/grafana/tree/master/packages/grafana-data/src/datetime
* Source code is in React/Typescript
* `datemath.test.ts` has some very useful use examples

**Comment by builder-247** [comment]
@mattco98 I believe you could be interested in working on this after you are done with GraphQL?

**Comment by mattco98** [comment]
Sure, sounds interesting
