### ISSUE TITLE
Rewrite getData

### ISSUE THREAD

**Issue by builder-247** [slothpixel/core#363]
The utility function getData in it's current form is - having undergone many changes to the way Hypixel API works, the logging output and behaviour is buggy and sometimes works in unintended ways.

This is also a good opportunity to switch from the deprecated `request` library to `axios` and utilize promises.

Goals for the rewrite:
* Use axios and promises
* Record Hypixel API response times for different endpoints
* Add max retries
* Provide more insightful logs
* Assure properly working logic

**Comment by Richienb** [comment]
@builder-247 I've started work on this feature. For now, I'm going to use [got](https://www.npmjs.com/package/got) since it has built-in retry logic and is a very popular HTTP package.
