### ISSUE TITLE
Using external modules to simplify functions

### ISSUE THREAD

**Issue by Richienb** [slothpixel/core#400]
Most logic implemented in the utility files already have much better-implemented versions on npm.

For example, `getNestedObject` is provided by [dot-prop](https://github.com/sindresorhus/dot-prop):
https://github.com/slothpixel/core/blob/f2bf6772a5a8a1d0aaac548f135001e515367e77/util/utility.js#L153-L165

and `pickKeys` is provided by [filter-obj](https://github.com/sindresorhus/filter-obj):
https://github.com/slothpixel/core/blob/f2bf6772a5a8a1d0aaac548f135001e515367e77/util/utility.js#L98-L122

Using well-maintained external modules should make our lives easier for the small price of an increase in dependency count.

**Comment by builder-247** [comment]
The functions defined in utilities serve their purpose, and the time it takes to switch them is better used elsewhere.

> small price of an increase in dependency count

I don't think weight of adding dependencies should be overlooked - increase in bundle size and larger attack surface are not worth the small benefits of using a package for everything.
