### ISSUE TITLE
Some items returning null to most if not, all values.

### ISSUE THREAD

**Issue by apollyon600** [slothpixel/core#431]
The GET request to https://api.slothpixel.me/api/skyblock/auctions/HOT_POTATO_BOOK
returned with its average price, along with its other values.. After that, the next day it returned
with
`{"average_price":null,"median_price":null,"standard_deviation":null,"min_price":null,"max_price":null,"sold":0}`

**Comment by Richienb** [comment]
Hot potato books aren't sold in the auction house.

**Comment by builder-247** [comment]
I think `HOT_POTATO_BOOK` is an example ID in the docs confusing people, we probably should change it to some other ID.
