### ISSUE TITLE
Create a new service to monitor hypixel player counts

### ISSUE THREAD

**Issue by builder-247** [slothpixel/core#55]
As described in https://github.com/HypixelDev/PublicAPI/issues/71

The service would
* Create a mineflayer bot to check to data from hypixel
  * would use `MC_USERNAME` and  `MC_PASSWORD` fields stored config.js
* Provide data for playercounts endpoint

**Comment by Dance-Dog** [comment]
Good news, Hypixel’s official gamecounts endpoint is now available to all users, so no more bots needed. (https://github.com/HypixelDev/PublicAPI/pull/83)

https://api.hypixel.net/gamecounts?key=YOUR_KEY
