### ISSUE TITLE
Tightly-Tied Hay Bales listed as TIGHTLY-TIED_HAY_BALE instead of TIGHTLY_TIED_HAY_BALE in bazaar item "related" key

### ISSUE THREAD

**Issue by csjh** [slothpixel/core#712]
Just a heads up that it should be TIGHTLY_TIED instead of TIGHTLY-TIED.

Might be present in other areas of the API but I assume the related items are hardcoded which would be where the error comes from.

**Comment by MattTheCuber** [comment]
This is actually stemming from slothpixel/hypixelconstants as seen in [here](https://github.com/slothpixel/hypixelconstants/blob/ca2f5f097b388e4e42292dd924fd0925ec6f60d5/build/skyblock_bazaar.json) and [here](https://github.com/slothpixel/hypixelconstants/blob/ca2f5f097b388e4e42292dd924fd0925ec6f60d5/json/skyblock_bazaar.json)
